### ISSUE TITLE
LinuxにRails環境を構築する。

### ISSUE THREAD

**Issue by kkawazoe** [systemlink/attendance#30]
- [x] VM上にLinuxをインストール
- [x] LinuxにRails環境を構築
- [x] LinuxにGitをインストール

**Comment by kkawazoe** [comment]
以下の環境を構築
 OS  :Ubuntu 14.04
 ruby:2.3.0
 rails:4.2.5

**Comment by inoh** [comment]
@kkawazoe 
#26 
このissueの関係だけどnode.jsが必要になるかも
もし事前にできるならnode.jsもインストールしておいてもらえると助かります

**Comment by kkawazoe** [comment]
@inoh 
分かりました。
しておきます。

**Comment by kkawazoe** [comment]
node.jsをインストールしました。
