### ISSUE TITLE
カレンダーに作業内容を表示するカンプを作成

### ISSUE THREAD

**Issue by inoh** [systemlink/attendance#42]
## 概要
- [x] カレンダーに作業内容を追加する
- [x] 文字が幅いっぱいになった場合は「...」で省略する
## UI

https://popapp.in/w/projects/56a2c7f9c674c6e20141e622/mockups/56bb9bb7064003c52f6722f3

**Comment by inoh** [comment]
@kkawazoe 
カレンダーのカンプを修正しました。
確認お願いします。

**Comment by kkawazoe** [comment]
@inoh 
確認しました。
「繰り返し」チェックボックスは役割的には複写機能と考えて良いですか。

**Comment by inoh** [comment]
@kkawazoe 
googleカレンダーをベースに考えていましたが細かな動きまで考えてなかったです。
これ実装しようと思うと一挙にボリュームが膨らむのでとりあえず画面にチェックボックスを配置するとこまでやってもらって実装はまた別途調整させてください

**Comment by kkawazoe** [comment]
@inoh 
分かりました。
