### ISSUE TITLE
祝日のリソース設計

### ISSUE THREAD

**Issue by inoh** [systemlink/attendance#46]

**Comment by inoh** [comment]
@kkawazoe 
- テーブル名は複数形で！確認したい場合はrailsの `pluralize`メソッドで確認できます
- `holiday_name` はテーブル名とかぶっていてくどいきがするので `name` でよいです
- year, month, day は一つのDate型にまとめてよいと思います。
- 備考の用途がなければ一旦削除して必要に応じてまた改めて追加してください。

**Comment by kkawazoe** [comment]
@inoh 
- テーブル名は複数形で！確認したい場合はrailsの `pluralize`メソッドで確認できます  
  →修正しました。
- `holiday_name` はテーブル名とかぶっていてくどいきがするので `name` でよいです  
  →修正しました。
- year, month, day は一つのDate型にまとめてよいと思います。  
  →一つにまとめました。date_ymdとしましたが「_ymd」の部分はあるのとないのとでは  
  　どちらがいいんでしょうか？
- 備考の用途がなければ一旦削除して必要に応じてまた改めて追加してください。  
  →具体的な用途を想定してはいないので削除しました。

**Comment by inoh** [comment]
`_ymd` は Dateという型で判断できるので不要かと思います。

**Comment by inoh** [comment]
:+1:
