### ISSUE TITLE
3/26に振り返りたいこと

### ISSUE THREAD

**Issue by inoh** [systemlink/attendance#52]
- [x] 面接から引継ぎまでの段取り
- [x] 学習方法
- [x] 進捗管理方法
- [x] 勉強会のお題の作り方
- [x] 勉強会をやる期間
- [x] 川添くんのボトルネック

**Comment by kkawazoe** [comment]
@inoh 
追加でしたいのが、
- [x] 面接から引継ぎまでの段取り
- [x] 学習方法  

ですね。
